name: Accessibility Testing

on:
  pull_request:
    branches: [main]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Start local server
        run: |
          npm run preview &
          sleep 5

      - name: Run pa11y-ci
        run: npx pa11y-ci --sitemap http://localhost:4321/sitemap-index.xml
